### ISSUE TITLE
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later

### ISSUE THREAD

**Issue by TofPlay** [algolia/algoliasearch-client-swift#80] opened 2016-06-28 07:14 UTC
Hi,
Following Algolia Search with Carthage:
* `carthage version`: 0.16.2
* `xcodebuild -version`: Xcode 7.3.1 Build version 7D1014
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "algolia/algoliasearch-client-swift" == 3.2.1
```
**Cartage Output**
```
$ carthage update --platform iOS
*** Cloning algoliasearch-client-swift
*** Checking out algoliasearch-client-swift at "3.2.1"
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
```
 I don't have those warnings with Algolia Search version 2.3. Something must be wrong configured in your project.

**Comment by TofPlay** [comment] 2016-06-28 08:39
**Update**: If I try to upload to the App Store my project with Algolia version 3.2.1 Xcode display this message:

![upload to appstore with algolia 3 2 1](https://cloud.githubusercontent.com/assets/1082222/16409170/8277b726-3d1c-11e6-895f-741d8f1b5819.png)

**Comment by clement-leprovost** [comment] 2016-06-28 08:44
@TofPlay Regarding the App Store warning, this is a duplicate of #75 and should have been fixed yesterday.

Tip: try explicitly using master HEAD, otherwise Carthage will likely pick up the last released version, which does not contain this fix. A new release is planned, but we have other pending changes to ship, so it is not yet available.

**Comment by TofPlay** [comment] 2016-06-28 08:57
@clement-leprovost with the `master` branch that generate a couple of warnings:
```
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:87:12: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
/Carthage/Checkouts/algoliasearch-client-swift/Source/Request.swift:96:16: warning: unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true
```

**Comment by clement-leprovost** [comment] 2016-06-28 09:10
Yes, that's expected (as explained in #75). We cannot avoid those warnings, as the source code is compatible with iOS 7 (as requested in #62), but package managers like Carthage and CocoaPods build dynamic frameworks that are only supported on iOS 8.

**Comment by TofPlay** [comment] 2016-06-28 09:12
That strange because with 2.3 I don't have those warnings

**Comment by TofPlay** [comment] 2016-06-28 09:55
With the branch `master` upload has successfully completed 👍
Thanks @clement-leprovost for your support 🙂

![image](https://cloud.githubusercontent.com/assets/1082222/16411326/d1eeee82-3d26-11e6-8f20-2cee015d9adf.png)

**Closed** 2016-06-28 09:59 UTC

**Comment by clement-leprovost** [comment] 2016-06-28 10:01
@TofPlay You're welcome! Glad to know you're back on track. :)

Regarding version 2.3, it's normal that you didn't get the warnings: minimum OS version was 7.0, so the runtime check was legitimate. Again, this whole thing is a compromise: we can't both support iOS 7 in the source code *and* allow building dynamic frameworks *and* avoid the warnings...

**Comment by TofPlay** [comment] 2016-06-28 11:38
Version 2.3 I also use it as a dynamic framework with Carthage for our application in iOS 8
Anyway I'm much more interested about a support of Swift 3 for Algolia. 😊

**Comment by clement-leprovost** [comment] 2016-06-28 11:55
@TofPlay Then I encourage you to watch issue #74 (Swift 2.3/3.0 support).
