### ISSUE TITLE
Issue: AbstractQuery (with Backendless-osx-SDK)

### ISSUE THREAD

**Issue by edl00k** [algolia/algoliasearch-client-swift#154] opened 2016-11-18 20:09 UTC
Hi @clement-leprovost,
Can you help me with issue? 
`...Pods/Headers/Public/Backendless-osx-SDK/AbstractQuery.h:26:1: Duplicate interface definition for class 'AbstractQuery'` / commit 86937672ce49de87dabef22725db6d4437887184

Just check this case:

platform :osx, '10.11'
    pod 'Backendless-osx-SDK'
    pod 'AlgoliaSearch-Client-Swift'
end

It's surprise that cocoapods (or design of framework) does not solves this issue / duplicating class names in difference frameworks

Thanks

**Comment by clement-leprovost** [comment] 2016-11-18 21:28
Hello @edl00k,

I can't know for sure since I don't have access to your code, but I think your problem likely stems from the fact that you are using `#import` instead of `@import`.

If you `#import` directly the bridging header `AlgoliaSearch-Swift.h`, the two classes will end up in the global namespace and collide. But if you use `@import`, they will be implicitly namespaced and should not collide any longer.

See this small POC below:

```
#import "Backendless.h"

// Importing the bridging header directly won't work:
// #import "AlgoliaSearch-Swift.h"

// Importing the  module should work, as it is automatically namespaced:
@import AlgoliaSearch;


int main(int argc, const char * argv[]) {
    FileService* fileService = [[FileService alloc] init]; // this class is from Backendless
    [fileService exists:@"foo"];
    AbstractQuery* query = [[AbstractQuery alloc] init]; // this class is from AlgoliaSearch
    [query setParameterWithName:@"foo" to:@"bar"];
}
```

**Comment by edl00k** [comment] 2016-11-18 23:02
Thank for quick reply,
I found solution but anyway it's strange. The reason was in order of import. You can check it out here [test project](https://github.com/edl00k/DuplicateNames.git)

In a nutshell:
`// Issue`
`@import AlgoliaSearch;`
`#import <Backendless-osx-SDK/Backendless.h>`
` `
`// No Issue`
`#import <Backendless-osx-SDK/Backendless.h>`
`@import AlgoliaSearch;`

**Comment by clement-leprovost** [comment] 2016-11-19 00:07
@edl00k Indeed... I think it would not occur if Backendless was provided as a framework rather than a static library (since it would allow you to `@import` it as well). But I guess you have little control over that, so at least I am glad to read that you found a workaround. :)

Closing this issue, as this is not a bug in Algolia Search IMHO.

**Closed by clement-leprovost** 2016-11-19 00:07 UTC
Labels: bug
